workspace:
  base: /test
  path: behat-transformation-context

services:
  web:
    image: ${IMAGE_PHP=fpfis/php56-build:latest}
    environment:
     - DOCUMENT_ROOT=/test/behat-transformation-context

pipeline:
  composer-install:
    group: prepare
    image: ${IMAGE_PHP=fpfis/php56-build:latest}
    volumes:
      - /cache:/cache
    commands:
      - composer install

  grumphp:
    group: test
    image: ${IMAGE_PHP=fpfis/php56-build:latest}
    commands:
      - ./vendor/bin/grumphp run

  behat:
    group: test
    image: fpfis/php71-build:latest
    commands:
      - ./vendor/bin/behat

matrix:
  IMAGE_PHP:
    - fpfis/php56-build:latest
    - fpfis/php71-build:latest
