name: ci
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  automated-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["8.3"]
    env:
      PHP_VERSION: ${{ matrix.php_version }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start services with Docker Compose
        run: docker-compose up -d

      - run: docker compose exec -T web composer self-update --2 # Fix for broken GitHub pipeline.

      - name: Build dependencies
        run: docker-compose exec -T web composer install --ansi --no-progress

      - name: Run code sniffer
        run: docker-compose exec -T web ./vendor/bin/grumphp run

      - name: Run tests
        run: docker-compose exec -T web ./vendor/bin/behat --strict
